model:
  target: model.classic_model.ResNet.ResNetClassifier
  params:
    num_classes: 2
    pretrained: True
    learning_rate: 1e-3

data:
  target: data.dataset_lightning_wrap.DataModuleFromConfig
  params:
    batch_size: 16
    wrap: true
    train:
      target: data.dataset_custom.Lung.ultrasound_lung.LungDataset
      params:
        data_dir: /mnt/Dataset/Lung/process_data/step3_total_data_prepare
        split: train
    validation:
      target: data.dataset_custom.Lung.ultrasound_lung.LungDataset
      params:
        data_dir: /mnt/Dataset/Lung/process_data/step3_total_data_prepare
        split: test
    test:
      target: data.dataset_custom.Lung.ultrasound_lung.LungDataset
      params:
        data_dir: /mnt/Dataset/Lung/process_data/step3_total_data_prepare
        split: test