model:
  target: model.classic_model.ResNet_Tabular.FusionModel
  params:
    num_classes: 2
    struct_feature_dim: 11
    pretrained: True
    learning_rate: 0.0001

data:
  target: data.dataset_lightning_wrap.DataModuleFromConfig
  params:
    batch_size: 8
    wrap: true
    train:
      target: data.dataset_custom.tongue.tongue_IgA.TongueDataset
      params:
        data_dir: /media/ps/data-ssd/home-ssd/wengtaohan/Dataset/tongue/tongue_IgA
        data_type: multi
        split: train
        data_phase: tongue
        image_format: JPG
    validation:
      target: data.dataset_custom.tongue.tongue_IgA.TongueDataset
      params:
        data_dir: /media/ps/data-ssd/home-ssd/wengtaohan/Dataset/tongue/tongue_IgA
        data_type: multi
        split: test
        data_phase: tongue
        image_format: JPG
    test:
      target: data.dataset_custom.tongue.tongue_IgA.TongueDataset
      params:
        data_dir: /media/ps/data-ssd/home-ssd/wengtaohan/Dataset/tongue/tongue_IgA
        data_type: multi
        split: test
        data_phase: tongue
        image_format: JPG